#include "codegen.h"
#include <stdlib.h>
#include <string.h>

void codegen_init(CodeGen* cg, const char* output_filename) {
    cg->output_file = fopen(output_filename, "w");
    cg->indentation = 0;
    
    if (!cg->output_file) {
        fprintf(stderr, "CodeGen Error: Could not create output file %s\n", output_filename);
        exit(1);
    }
    
    // Write the standard C headers for our native output
    fprintf(cg->output_file, "/* Auto-generated by VoLang Compiler */\n");
    fprintf(cg->output_file, "#include <stdio.h>\n");
    fprintf(cg->output_file, "#include <stdlib.h>\n\n");
    
    // Start the native main function
    fprintf(cg->output_file, "int main() {\n");
    cg->indentation++;
}

// Helper to write indentation spaces
static void write_indent(CodeGen* cg) {
    for (int i = 0; i < cg->indentation * 4; i++) {
        fputc(' ', cg->output_file);
    }
}

// Recursive function to turn AST nodes into C Code string
static void generate_node(CodeGen* cg, AstNode* node) {
    if (!node) return;

    switch (node->type) {
        case AST_LET_STATEMENT:
            write_indent(cg);
            // VoLang uses dynamic types (let), but for max speed in C, 
            // we will default to 'long long' (64-bit int) for now until type inference is added.
            fprintf(cg->output_file, "long long %.*s = ", 
                    (int)node->data.let_stmt.name->length, 
                    node->data.let_stmt.name->value);
                    
            generate_node(cg, node->data.let_stmt.value);
            fprintf(cg->output_file, ";\n");
            break;

        case AST_RETURN_STATEMENT:
            write_indent(cg);
            fprintf(cg->output_file, "return ");
            generate_node(cg, node->data.return_stmt.return_value);
            fprintf(cg->output_file, ";\n");
            break;

        case AST_INFIX_EXPRESSION:
            fprintf(cg->output_file, "(");
            generate_node(cg, node->data.infix.left);
            fprintf(cg->output_file, " %.*s ", 
                    (int)node->data.infix.operator_len, 
                    node->data.infix.operator_str);
            generate_node(cg, node->data.infix.right);
            fprintf(cg->output_file, ")");
            break;

        case AST_INTEGER_LITERAL:
            fprintf(cg->output_file, "%lld", node->data.int_literal.value);
            break;

        case AST_IDENTIFIER:
            fprintf(cg->output_file, "%.*s", 
                    (int)node->data.ident.length, 
                    node->data.ident.value);
            break;

        case AST_EXPRESSION_STATEMENT:
            write_indent(cg);
            generate_node(cg, node->data.expression_stmt);
            fprintf(cg->output_file, ";\n");
            break;

        default:
            fprintf(stderr, "CodeGen Warning: Unhandled AST node type\n");
            break;
    }
}

int codegen_program(CodeGen* cg, Program* program) {
    for (size_t i = 0; i < program->statement_count; i++) {
        generate_node(cg, program->statements[i]);
    }
    return 1;
}

void codegen_close(CodeGen* cg) {
    cg->indentation--;
    fprintf(cg->output_file, "\n    return 0;\n}\n");
    fclose(cg->output_file);
}
